export const testID = {
  mainContainerTestid: "main-container-view",
  buttonContainerTestid: "button-container-view",
  imageContainerTestid: "image-container-view",
  imageContainerImageTestid: "image-banner-image",
  scrollViewTestid: "main-scroll-view",
  pressableConnectTestid: "index-file-pressable-connect-bluetooth",
  pressableConnectTextTestid: "index-file-pressable-connect-bluetooth-text",
  pressableStatusTestid: "index-file-pressable-bluetooth-status",
  pressableStatusTextTestid: "index-file-pressable-bluetooth-status-text",
  buttonContainerBodyTestid: "button-container-body-view",
  pressableOffTestid: "index-file-pressable-off-button",
  pressableOffTextTestid: "index-file-pressable-off-button-text",
  pressable25Testid: "index-file-pressable-25-button",
  pressable25TextTestid: "index-file-pressable-25-button-text",
  pressable50Testid: "index-file-pressable-50-button",
  pressable50TextTestid: "index-file-pressable-50-button-text",
  pressable75Testid: "index-file-pressable-75-button",
  pressable75TextTestid: "index-file-pressable-75-button-text",
  pressable100Testid: "index-file-pressable-100-button",
  pressable100TextTestid: "index-file-pressable-100-button-text",
  pressablePoleupTestid: "index-file-pressable-pole-up-button",
  pressablePoleupTextTestid: "index-file-pressable-pole-up-button-text",
  pressablePoledownTestid: "index-file-pressable-pole-down-button",
  pressablePoledownTextTestid: "index-file-pressable-pole-down-button-text",
};
